### ISSUE TITLE
Wrong Date in parsed by bucketPrefix

### ISSUE THREAD

**Issue by mtx62** [parse-community/parse-server-s3-adapter#88]
Hi,
Thank you for this great package and your effort.
I'm facing trouble that when I set the path of bucketPrefix by Date, For example:

```
    const date = new Date();
    const year = date.getFullYear();
    const month = date.getMonth() + 1;
    const day = date.getDate();

    const imagePath = `uploaded/${year}/${month}/${day}/`

    var s3Adapter = new S3Adapter('test', {
      bucketPrefix: imagePath,
    });
```

The first day I execute this code the path is working fine, 
Example: uploaded/2020/4/15/

But after a complete day of running in PM2, the date become wrong,
Example: should be shown (uploaded/2020/4/**16**/) but instead it shows (uploaded/2020/4/**15**/)

I checked the date using Parse Cloud and it's working right

I know it's a wired issue but I thought I muse report about it.

Best regards.
Abdulaziz Noor

**Comment by davimacedo** [comment]
Your code is probably running on your process initialization, and, since your process propably hasn't restarted, the bucketPrefix will continue being the one in the date that you initialized it, until you restart the process. Anyways, I don't recommend you initializing the prefix like this. I guess that, after restarting the server in another day, the files that you've uploaded in the days before will not be accessible anymore, since they are in another bucket :)
